-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgWx3QekBf0zCcmgdF
3Fx8y/DGF/rQb8WG+xlxfr7mkDGgCgYIKoZIzj0DAQehRANCAARlZc5Itj/e66xa
D/ElTwOgKRb+YgFlba1anwUotYd5Ri35BW+v4wweXsd3sAGZ2fMMsJNdLqZNZqEI
dChg9GZO
-----END PRIVATE KEY-----